[2025-06-01T20:46:04.365+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-01T20:46:04.627+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer manual__2025-06-01T18:14:25.745126+00:00 [queued]>
[2025-06-01T20:46:04.654+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer manual__2025-06-01T18:14:25.745126+00:00 [queued]>
[2025-06-01T20:46:04.705+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-06-01T20:46:04.757+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): start_spark_consumer> on 2025-06-01 18:14:25.745126+00:00
[2025-06-01T20:46:04.801+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'log_monitoring_dag', 'start_spark_consumer', 'manual__2025-06-01T18:14:25.745126+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/log_monitoring_dag.py', '--cfg-path', '/tmp/tmpzmfsygtl']
[2025-06-01T20:46:04.866+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=179) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-01T20:46:04.947+0000] {standard_task_runner.py:105} INFO - Job 146: Subtask start_spark_consumer
[2025-06-01T20:46:04.949+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-06-01T20:46:04.980+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T20:46:05.121+0000] {task_command.py:467} INFO - Running <TaskInstance: log_monitoring_dag.start_spark_consumer manual__2025-06-01T18:14:25.745126+00:00 [running]> on host 61a0313acf02
[2025-06-01T20:46:05.328+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='log_monitoring_dag' AIRFLOW_CTX_TASK_ID='start_spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T18:14:25.745126+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-01T18:14:25.745126+00:00'
[2025-06-01T20:46:05.329+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-01T20:46:05.388+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-01T20:46:05.392+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            docker run --rm             --network realtime_log_monitoring_default             -v /opt/***/app:/app             bitnami/spark:3.3.0             spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 /app/log_consumer.py\n        ']
[2025-06-01T20:46:05.464+0000] {subprocess.py:86} INFO - Output:
[2025-06-01T20:46:17.374+0000] {job.py:229} INFO - Heartbeat recovered after 13.41 seconds
[2025-06-01T20:46:28.229+0000] {job.py:229} INFO - Heartbeat recovered after 11.11 seconds
[2025-06-01T20:46:51.271+0000] {job.py:229} INFO - Heartbeat recovered after 24.23 seconds
[2025-06-01T20:47:23.295+0000] {job.py:229} INFO - Heartbeat recovered after 13.41 seconds
[2025-06-01T20:47:31.352+0000] {job.py:229} INFO - Heartbeat recovered after 12.12 seconds
[2025-06-01T20:47:50.724+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m20:47:50.72 [0m
[2025-06-01T20:47:50.762+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m20:47:50.72 [0m[1mWelcome to the Bitnami spark container[0m
[2025-06-01T20:47:50.763+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m20:47:50.72 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-06-01T20:47:50.764+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m20:47:50.73 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-06-01T20:47:50.765+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m20:47:50.73 [0m
[2025-06-01T20:47:51.705+0000] {subprocess.py:93} INFO - 
[2025-06-01T20:48:19.444+0000] {job.py:229} INFO - Heartbeat recovered after 11.93 seconds
[2025-06-01T20:48:46.230+0000] {job.py:229} INFO - Heartbeat recovered after 19.78 seconds
[2025-06-01T20:49:00.223+0000] {job.py:229} INFO - Heartbeat recovered after 26.05 seconds
[2025-06-01T20:49:15.538+0000] {job.py:229} INFO - Heartbeat recovered after 15.68 seconds
[2025-06-01T20:49:30.284+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-06-01T20:49:30.579+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
[2025-06-01T20:49:30.583+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-06-01T20:49:30.672+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-06-01T20:49:30.687+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-cd519d79-e8d2-4829-9a5c-1c6d14269428;1.0
[2025-06-01T20:49:30.694+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-06-01T20:49:46.714+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0 in central
[2025-06-01T20:52:58.529+0000] {job.py:229} INFO - Heartbeat recovered after 191.90 seconds
[2025-06-01T20:54:21.914+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-06-01T20:55:39.925+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-06-01T20:56:18.091+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-06-01T20:59:35.246+0000] {job.py:229} INFO - Heartbeat recovered after 390.73 seconds
[2025-06-01T21:00:34.419+0000] {job.py:229} INFO - Heartbeat recovered after 33.05 seconds
[2025-06-01T21:02:34.652+0000] {job.py:229} INFO - Heartbeat recovered after 137.47 seconds
[2025-06-01T21:02:41.609+0000] {job.py:229} INFO - Heartbeat recovered after 15.54 seconds
[2025-06-01T21:03:39.863+0000] {job.py:229} INFO - Heartbeat recovered after 58.82 seconds
[2025-06-01T21:03:50.473+0000] {job.py:229} INFO - Heartbeat recovered after 27.69 seconds
[2025-06-01T21:04:10.581+0000] {job.py:229} INFO - Heartbeat recovered after 12.80 seconds
[2025-06-01T21:04:22.534+0000] {job.py:229} INFO - Heartbeat recovered after 12.54 seconds
[2025-06-01T21:05:06.639+0000] {job.py:229} INFO - Heartbeat recovered after 12.24 seconds
[2025-06-01T21:05:20.335+0000] {job.py:229} INFO - Heartbeat recovered after 14.83 seconds
[2025-06-01T21:05:40.357+0000] {job.py:229} INFO - Heartbeat recovered after 23.14 seconds
[2025-06-01T21:05:50.280+0000] {job.py:229} INFO - Heartbeat recovered after 11.32 seconds
[2025-06-01T21:06:44.892+0000] {job.py:229} INFO - Heartbeat recovered after 26.49 seconds
[2025-06-01T21:06:52.950+0000] {job.py:229} INFO - Heartbeat recovered after 27.45 seconds
[2025-06-01T21:07:21.190+0000] {job.py:229} INFO - Heartbeat recovered after 11.51 seconds
[2025-06-01T21:07:32.940+0000] {job.py:229} INFO - Heartbeat recovered after 11.76 seconds
[2025-06-01T21:08:02.766+0000] {job.py:229} INFO - Heartbeat recovered after 17.94 seconds
[2025-06-01T21:08:17.449+0000] {job.py:229} INFO - Heartbeat recovered after 17.67 seconds
[2025-06-01T21:08:28.117+0000] {job.py:229} INFO - Heartbeat recovered after 12.00 seconds
[2025-06-01T21:09:08.939+0000] {job.py:229} INFO - Heartbeat recovered after 14.03 seconds
[2025-06-01T21:11:05.591+0000] {job.py:229} INFO - Heartbeat recovered after 41.63 seconds
[2025-06-01T21:12:01.845+0000] {job.py:229} INFO - Heartbeat recovered after 91.79 seconds
[2025-06-01T21:13:12.968+0000] {job.py:229} INFO - Heartbeat recovered after 10.85 seconds
[2025-06-01T21:14:26.870+0000] {job.py:229} INFO - Heartbeat recovered after 53.40 seconds
[2025-06-01T21:14:35.708+0000] {job.py:229} INFO - Heartbeat recovered after 54.66 seconds
[2025-06-01T21:18:38.157+0000] {job.py:229} INFO - Heartbeat recovered after 16.19 seconds
[2025-06-01T21:19:17.789+0000] {job.py:229} INFO - Heartbeat recovered after 40.72 seconds
[2025-06-01T21:19:31.361+0000] {job.py:229} INFO - Heartbeat recovered after 15.04 seconds
[2025-06-01T21:20:10.215+0000] {job.py:229} INFO - Heartbeat recovered after 22.66 seconds
[2025-06-01T21:20:27.205+0000] {job.py:229} INFO - Heartbeat recovered after 17.25 seconds
[2025-06-01T21:21:39.010+0000] {job.py:229} INFO - Heartbeat recovered after 13.32 seconds
[2025-06-01T21:22:59.799+0000] {job.py:229} INFO - Heartbeat recovered after 13.46 seconds
[2025-06-01T21:24:54.152+0000] {job.py:229} INFO - Heartbeat recovered after 11.72 seconds
[2025-06-01T21:25:05.494+0000] {job.py:229} INFO - Heartbeat recovered after 12.71 seconds
[2025-06-01T21:26:26.811+0000] {job.py:229} INFO - Heartbeat recovered after 15.47 seconds
[2025-06-01T21:26:45.198+0000] {job.py:229} INFO - Heartbeat recovered after 13.31 seconds
[2025-06-01T21:27:02.047+0000] {job.py:229} INFO - Heartbeat recovered after 11.13 seconds
[2025-06-01T21:27:12.766+0000] {job.py:229} INFO - Heartbeat recovered after 10.78 seconds
[2025-06-01T21:27:42.067+0000] {job.py:229} INFO - Heartbeat recovered after 16.42 seconds
[2025-06-01T21:28:32.810+0000] {job.py:229} INFO - Heartbeat recovered after 19.61 seconds
[2025-06-01T21:29:06.918+0000] {job.py:229} INFO - Heartbeat recovered after 11.63 seconds
[2025-06-01T21:31:48.153+0000] {job.py:229} INFO - Heartbeat recovered after 72.34 seconds
[2025-06-01T21:32:07.608+0000] {job.py:229} INFO - Heartbeat recovered after 20.46 seconds
[2025-06-01T21:32:27.434+0000] {job.py:229} INFO - Heartbeat recovered after 13.80 seconds
[2025-06-01T21:32:47.205+0000] {job.py:229} INFO - Heartbeat recovered after 12.14 seconds
[2025-06-01T21:37:16.771+0000] {job.py:229} INFO - Heartbeat recovered after 11.63 seconds
[2025-06-01T21:39:13.130+0000] {job.py:229} INFO - Heartbeat recovered after 19.82 seconds
[2025-06-01T21:39:23.890+0000] {job.py:229} INFO - Heartbeat recovered after 13.35 seconds
[2025-06-01T21:39:31.929+0000] {job.py:229} INFO - Heartbeat recovered after 12.41 seconds
[2025-06-01T21:39:55.050+0000] {job.py:229} INFO - Heartbeat recovered after 10.85 seconds
[2025-06-01T21:40:23.268+0000] {job.py:229} INFO - Heartbeat recovered after 29.48 seconds
[2025-06-01T21:42:52.197+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 233, in heartbeat
    heartbeat_callback(session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/local_task_job_runner.py", line 284, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2358, in refresh_from_db
    _refresh_from_db(task_instance=self, session=session, lock_for_update=lock_for_update)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 872, in _refresh_from_db
    ti = TaskInstance.get_task_instance(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2344, in get_task_instance
    return query.one_or_none()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-06-01T21:44:26.726+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-06-01T21:45:28.002+0000] {local_task_job_runner.py:228} ERROR - Heartbeat time limit exceeded!
[2025-06-01T21:45:36.458+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-06-01T21:45:42.864+0000] {process_utils.py:132} INFO - Sending 15 to group 196. PIDs of all processes in the group: [218, 241, 196]
[2025-06-01T21:45:49.041+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 196
[2025-06-01T21:47:01.698+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-01T21:48:12.193+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-06-01T21:46:50.141+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=196, name='airflow task ru', status='running', started='20:46:03') did not respond to SIGTERM. Trying SIGKILL
[2025-06-01T21:48:38.211+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=218, name='bash', status='zombie', started='20:46:04') did not respond to SIGTERM. Trying SIGKILL
[2025-06-01T21:48:40.407+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=241, name='docker', status='sleeping', started='20:46:05') did not respond to SIGTERM. Trying SIGKILL
[2025-06-01T21:48:42.357+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 196
[2025-06-01T21:48:58.262+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=196, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='20:46:03') (196) terminated with exit code -9
[2025-06-01T21:49:00.031+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=218, name='bash', status='terminated', started='20:46:04') (218) terminated with exit code None
[2025-06-01T21:49:01.242+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-06-01T21:49:42.211+0000] {process_utils.py:161} ERROR - Process psutil.Process(pid=241, name='docker', status='sleeping', started='20:46:05') (241) could not be killed. Giving up.
[2025-06-01T21:49:42.325+0000] {standard_task_runner.py:190} ERROR - ('Job 146 was killed before it finished (likely due to running out of memory)', 'For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed')
