[2025-06-01T16:59:30.755+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-01T16:59:31.067+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T16:45:00+00:00 [queued]>
[2025-06-01T16:59:31.303+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T16:45:00+00:00 [queued]>
[2025-06-01T16:59:31.304+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-06-01T16:59:31.569+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): start_spark_consumer> on 2025-06-01 16:45:00+00:00
[2025-06-01T16:59:31.581+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'log_monitoring_dag', 'start_spark_consumer', 'scheduled__2025-06-01T16:45:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/log_monitoring_dag.py', '--cfg-path', '/tmp/tmpwaualkn9']
[2025-06-01T16:59:31.624+0000] {standard_task_runner.py:105} INFO - Job 45: Subtask start_spark_consumer
[2025-06-01T16:59:31.647+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=302) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-01T16:59:31.649+0000] {standard_task_runner.py:72} INFO - Started process 303 to run task
[2025-06-01T16:59:31.652+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T16:59:31.693+0000] {task_command.py:467} INFO - Running <TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T16:45:00+00:00 [running]> on host 61a0313acf02
[2025-06-01T16:59:31.695+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T16:59:31.845+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='log_monitoring_dag' AIRFLOW_CTX_TASK_ID='start_spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T16:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-01T16:45:00+00:00'
[2025-06-01T16:59:31.847+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-01T16:59:32.040+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-01T16:59:32.044+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run --rm --network realtime_log_monitoring_default -v /opt/***/app:/app bitnami/spark:3.3.0 spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 /app/log_consumer.py']
[2025-06-01T16:59:32.109+0000] {subprocess.py:86} INFO - Output:
[2025-06-01T16:59:40.860+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m16:59:40.85 [0m
[2025-06-01T16:59:40.862+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m16:59:40.86 [0m[1mWelcome to the Bitnami spark container[0m
[2025-06-01T16:59:40.863+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m16:59:40.86 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-06-01T16:59:40.865+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m16:59:40.86 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-06-01T16:59:40.866+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m16:59:40.86 [0m
[2025-06-01T16:59:40.876+0000] {subprocess.py:93} INFO - 
[2025-06-01T16:59:43.963+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-06-01T16:59:44.023+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
[2025-06-01T16:59:44.024+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-06-01T16:59:44.028+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-06-01T16:59:44.029+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-3f40359d-19d7-49b3-b4a9-e96c758212fe;1.0
[2025-06-01T16:59:44.030+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-06-01T16:59:48.822+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0 in central
[2025-06-01T16:59:49.318+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.2.0 in central
[2025-06-01T16:59:49.616+0000] {subprocess.py:93} INFO - 	found org.apache.kafka#kafka-clients;2.8.0 in central
[2025-06-01T16:59:49.949+0000] {subprocess.py:93} INFO - 	found org.lz4#lz4-java;1.7.1 in central
[2025-06-01T17:00:22.522+0000] {subprocess.py:93} INFO - 	found org.xerial.snappy#snappy-java;1.1.8.4 in central
[2025-06-01T17:00:32.768+0000] {job.py:229} INFO - Heartbeat recovered after 43.81 seconds
[2025-06-01T17:00:32.774+0000] {subprocess.py:93} INFO - 	found org.slf4j#slf4j-api;1.7.30 in central
[2025-06-01T17:00:40.467+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.1 in central
[2025-06-01T17:00:41.387+0000] {subprocess.py:93} INFO - 	found org.spark-project.spark#unused;1.0.0 in central
[2025-06-01T17:00:42.549+0000] {job.py:229} INFO - Heartbeat recovered after 39.81 seconds
[2025-06-01T17:00:42.895+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.1 in central
[2025-06-01T17:01:18.794+0000] {job.py:229} INFO - Heartbeat recovered after 29.11 seconds
[2025-06-01T17:01:25.757+0000] {subprocess.py:93} INFO - 	found org.apache.htrace#htrace-core4;4.1.0-incubating in central
[2025-06-01T17:01:44.914+0000] {job.py:229} INFO - Heartbeat recovered after 49.35 seconds
[2025-06-01T17:01:49.056+0000] {subprocess.py:93} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-06-01T17:01:53.028+0000] {subprocess.py:93} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-06-01T17:04:39.684+0000] {job.py:229} INFO - Heartbeat recovered after 162.96 seconds
[2025-06-01T17:04:39.815+0000] {subprocess.py:93} INFO - time="2025-06-01T17:04:39Z" level=error msg="error waiting for container: unexpected EOF"
[2025-06-01T17:04:39.928+0000] {subprocess.py:97} INFO - Command exited with return code 125
[2025-06-01T17:04:39.730+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-06-01T17:04:39.993+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=log_monitoring_dag, task_id=start_spark_consumer, run_id=scheduled__2025-06-01T16:45:00+00:00, execution_date=20250601T164500, start_date=20250601T165931, end_date=20250601T170439
[2025-06-01T17:04:40.208+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-01T17:04:40.210+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 45 for task start_spark_consumer (Bash command failed. The command returned a non-zero exit code 125.; 303)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-06-01T17:04:40.262+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-01T17:04:40.343+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-01T17:04:40.369+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
