[2025-06-01T23:57:13.263+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-01T23:57:16.725+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T23:40:00+00:00 [queued]>
[2025-06-01T23:57:20.142+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T23:40:00+00:00 [queued]>
[2025-06-01T23:57:20.160+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-06-01T23:57:26.032+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): start_spark_consumer> on 2025-06-01 23:40:00+00:00
[2025-06-01T23:57:28.010+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=584) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-01T23:57:28.698+0000] {standard_task_runner.py:72} INFO - Started process 592 to run task
[2025-06-01T23:57:30.151+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'log_monitoring_dag', 'start_spark_consumer', 'scheduled__2025-06-01T23:40:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/log_monitoring_dag.py', '--cfg-path', '/tmp/tmpmjbynox0']
[2025-06-01T23:57:30.263+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask start_spark_consumer
[2025-06-01T23:57:35.352+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T23:57:36.877+0000] {task_command.py:467} INFO - Running <TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T23:40:00+00:00 [running]> on host 2317d0480f96
[2025-06-01T23:57:37.227+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T23:57:40.605+0000] {job.py:229} INFO - Heartbeat recovered after 42.42 seconds
[2025-06-01T23:57:50.866+0000] {job.py:229} INFO - Heartbeat recovered after 11.40 seconds
[2025-06-01T23:57:51.316+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='log_monitoring_dag' AIRFLOW_CTX_TASK_ID='start_spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T23:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-01T23:40:00+00:00'
[2025-06-01T23:57:51.341+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-01T23:57:57.727+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-01T23:57:59.334+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            docker run --rm             --network realtime_log_monitoring_default             -v /opt/***/app:/app             bitnami/spark:3.3.0             spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 /app/log_consumer.py\n        ']
[2025-06-01T23:57:59.445+0000] {subprocess.py:86} INFO - Output:
[2025-06-01T23:59:46.533+0000] {job.py:229} INFO - Heartbeat recovered after 11.36 seconds
[2025-06-02T00:00:05.845+0000] {job.py:229} INFO - Heartbeat recovered after 22.75 seconds
[2025-06-02T00:00:23.369+0000] {job.py:229} INFO - Heartbeat recovered after 11.91 seconds
[2025-06-02T00:00:31.255+0000] {job.py:229} INFO - Heartbeat recovered after 11.16 seconds
[2025-06-02T00:01:22.561+0000] {job.py:229} INFO - Heartbeat recovered after 10.79 seconds
[2025-06-02T00:02:51.793+0000] {job.py:229} INFO - Heartbeat recovered after 11.71 seconds
[2025-06-02T00:03:03.293+0000] {job.py:229} INFO - Heartbeat recovered after 12.39 seconds
[2025-06-02T00:03:58.064+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2025-06-02T00:04:05.548+0000] {process_utils.py:132} INFO - Sending 15 to group 592. PIDs of all processes in the group: [599, 604, 592]
[2025-06-02T00:04:05.806+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 592
[2025-06-02T00:04:06.043+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-02T00:04:06.506+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-06-02T00:04:07.088+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-06-02T00:04:08.481+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=log_monitoring_dag, task_id=start_spark_consumer, run_id=scheduled__2025-06-01T23:40:00+00:00, execution_date=20250601T234000, start_date=20250601T235716, end_date=20250602T000408
