[2025-06-02T01:22:46.278+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-02T01:22:49.433+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-02T00:45:00+00:00 [queued]>
[2025-06-02T01:22:49.551+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-02T00:45:00+00:00 [queued]>
[2025-06-02T01:22:49.578+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-06-02T01:22:50.676+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): start_spark_consumer> on 2025-06-02 00:45:00+00:00
[2025-06-02T01:22:50.725+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'log_monitoring_dag', 'start_spark_consumer', 'scheduled__2025-06-02T00:45:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/log_monitoring_dag.py', '--cfg-path', '/tmp/tmp_9kin0va']
[2025-06-02T01:22:52.048+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask start_spark_consumer
[2025-06-02T01:22:50.773+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=521) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-02T01:22:52.231+0000] {standard_task_runner.py:72} INFO - Started process 523 to run task
[2025-06-02T01:23:14.980+0000] {job.py:229} INFO - Heartbeat recovered after 32.06 seconds
[2025-06-02T01:23:16.264+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-02T01:23:34.789+0000] {job.py:229} INFO - Heartbeat recovered after 20.62 seconds
[2025-06-02T01:23:36.016+0000] {task_command.py:467} INFO - Running <TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-02T00:45:00+00:00 [running]> on host 95af1ae74a08
[2025-06-02T01:23:36.018+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-02T01:23:36.468+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='log_monitoring_dag' AIRFLOW_CTX_TASK_ID='start_spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T00:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-02T00:45:00+00:00'
[2025-06-02T01:23:36.776+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-02T01:23:42.435+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-02T01:23:43.997+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            docker run --rm             --network realtime_log_monitoring_default             -v /opt/***/app:/app             bitnami/spark:3.3.0             spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 /app/log_consumer.py\n        ']
[2025-06-02T01:23:49.573+0000] {subprocess.py:86} INFO - Output:
[2025-06-02T01:23:53.400+0000] {job.py:229} INFO - Heartbeat recovered after 11.84 seconds
[2025-06-02T01:24:30.542+0000] {job.py:229} INFO - Heartbeat recovered after 14.48 seconds
[2025-06-02T01:25:24.278+0000] {job.py:229} INFO - Heartbeat recovered after 17.68 seconds
[2025-06-02T01:25:47.882+0000] {job.py:229} INFO - Heartbeat recovered after 17.54 seconds
[2025-06-02T01:25:59.596+0000] {job.py:229} INFO - Heartbeat recovered after 13.27 seconds
[2025-06-02T01:26:09.761+0000] {job.py:229} INFO - Heartbeat recovered after 11.72 seconds
[2025-06-02T01:26:16.900+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:26:16.89 [0m
[2025-06-02T01:26:16.902+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:26:16.90 [0m[1mWelcome to the Bitnami spark container[0m
[2025-06-02T01:26:16.904+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:26:16.90 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-06-02T01:26:16.906+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:26:16.90 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-06-02T01:26:16.944+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:26:16.90 [0m
[2025-06-02T01:26:17.339+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:26:55.714+0000] {job.py:229} INFO - Heartbeat recovered after 11.29 seconds
[2025-06-02T01:27:59.980+0000] {job.py:229} INFO - Heartbeat recovered after 43.66 seconds
[2025-06-02T01:28:11.727+0000] {job.py:229} INFO - Heartbeat recovered after 11.90 seconds
[2025-06-02T01:28:38.164+0000] {job.py:229} INFO - Heartbeat recovered after 16.67 seconds
[2025-06-02T01:28:56.255+0000] {job.py:229} INFO - Heartbeat recovered after 21.97 seconds
[2025-06-02T01:29:15.732+0000] {job.py:229} INFO - Heartbeat recovered after 19.80 seconds
[2025-06-02T01:29:28.318+0000] {job.py:229} INFO - Heartbeat recovered after 12.92 seconds
[2025-06-02T01:29:45.470+0000] {job.py:229} INFO - Heartbeat recovered after 17.47 seconds
[2025-06-02T01:30:02.195+0000] {job.py:229} INFO - Heartbeat recovered after 17.38 seconds
[2025-06-02T01:30:14.869+0000] {job.py:229} INFO - Heartbeat recovered after 12.93 seconds
[2025-06-02T01:30:30.727+0000] {job.py:229} INFO - Heartbeat recovered after 16.13 seconds
[2025-06-02T01:30:47.664+0000] {job.py:229} INFO - Heartbeat recovered after 18.03 seconds
[2025-06-02T01:30:59.027+0000] {job.py:229} INFO - Heartbeat recovered after 11.87 seconds
[2025-06-02T01:31:13.734+0000] {job.py:229} INFO - Heartbeat recovered after 15.08 seconds
[2025-06-02T01:31:28.051+0000] {job.py:229} INFO - Heartbeat recovered after 14.36 seconds
[2025-06-02T01:31:40.452+0000] {job.py:229} INFO - Heartbeat recovered after 12.58 seconds
[2025-06-02T01:31:55.319+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-06-02T01:31:55.887+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
[2025-06-02T01:31:55.888+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-06-02T01:31:55.903+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-06-02T01:31:55.976+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-449ede40-03c9-4a28-9155-3da76ca1a460;1.0
[2025-06-02T01:31:56.040+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-06-02T01:32:11.833+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-02T01:32:12.012+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-02T01:32:12.326+0000] {job.py:229} INFO - Heartbeat recovered after 12.35 seconds
[2025-06-02T01:32:32.004+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 36573ms :: artifacts dl 0ms
[2025-06-02T01:32:32.278+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-06-02T01:32:32.384+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-02T01:32:32.386+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-06-02T01:32:32.387+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-06-02T01:32:32.540+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-02T01:32:32.545+0000] {subprocess.py:93} INFO - 	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2025-06-02T01:32:32.546+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-02T01:32:32.547+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:32.547+0000] {subprocess.py:93} INFO - :: problems summary ::
[2025-06-02T01:32:32.756+0000] {subprocess.py:93} INFO - :::: WARNINGS
[2025-06-02T01:32:32.756+0000] {subprocess.py:93} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-02T01:32:32.781+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:32.782+0000] {subprocess.py:93} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-02T01:32:32.782+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:32.783+0000] {subprocess.py:93} INFO - 		module not found: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0
[2025-06-02T01:32:32.783+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:32.784+0000] {subprocess.py:93} INFO - 	==== local-m2-cache: tried
[2025-06-02T01:32:32.784+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:32.785+0000] {subprocess.py:93} INFO - 	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-02T01:32:32.785+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:32.785+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-02T01:32:33.030+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.031+0000] {subprocess.py:93} INFO - 	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-02T01:32:33.032+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.033+0000] {subprocess.py:93} INFO - 	==== local-ivy-cache: tried
[2025-06-02T01:32:33.033+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.034+0000] {subprocess.py:93} INFO - 	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.2.0/ivys/ivy.xml
[2025-06-02T01:32:33.034+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.035+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-02T01:32:33.106+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.178+0000] {subprocess.py:93} INFO - 	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.2.0/jars/spark-sql-kafka-0-10_2.12.jar
[2025-06-02T01:32:33.204+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.278+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-06-02T01:32:33.279+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.279+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-02T01:32:33.279+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.280+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-02T01:32:33.280+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.577+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-02T01:32:33.587+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.588+0000] {subprocess.py:93} INFO - 	==== spark-packages: tried
[2025-06-02T01:32:33.667+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.669+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-02T01:32:33.670+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.670+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-02T01:32:33.671+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.672+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-02T01:32:33.672+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.673+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-02T01:32:33.674+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.674+0000] {subprocess.py:93} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2025-06-02T01:32:33.675+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.676+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-02T01:32:33.702+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.703+0000] {subprocess.py:93} INFO - 		:: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0: not found
[2025-06-02T01:32:33.703+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.948+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-02T01:32:34.121+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:34.199+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:34.307+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:34.420+0000] {subprocess.py:93} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-06-02T01:32:34.421+0000] {subprocess.py:93} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0: not found]
[2025-06-02T01:32:34.430+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
[2025-06-02T01:32:34.430+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-06-02T01:32:34.430+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2025-06-02T01:32:34.431+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2025-06-02T01:32:34.431+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2025-06-02T01:32:34.432+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2025-06-02T01:32:34.432+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2025-06-02T01:32:34.432+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2025-06-02T01:32:34.433+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2025-06-02T01:32:34.433+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-06-02T01:32:55.150+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-02T01:33:05.202+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-02T01:33:07.416+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=log_monitoring_dag, task_id=start_spark_consumer, run_id=scheduled__2025-06-02T00:45:00+00:00, execution_date=20250602T004500, start_date=20250602T012249, end_date=20250602T013306
[2025-06-02T01:33:09.357+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-02T01:33:09.388+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 67 for task start_spark_consumer (Bash command failed. The command returned a non-zero exit code 1.; 523)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-02T01:33:09.791+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-02T01:33:14.519+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-06-02T01:33:15.991+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-02T01:33:16.688+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
